// 검색 / 관련기사 / 홈페이지 히어로 슬라이더·최신기사 리스트 자동 렌더링이 공유하는 기사 메타데이터
// 새 기사를 발행할 때마다 이 배열에 항목 하나를 추가할 것.
window.ARTICLES_DATA = [
  {
    slug: "high-beam-etiquette-guide-2026",
    title: "\"상대 운전자 눈이 부셨다면\"… 상향등, 이럴 때만 쓰세요",
    date: "2026-08-01",
    image: "highbeam_night_expressway_lighttrails.webp",
    categories: ["news"],
    tags: ["상향등에티켓", "하이빔사용법", "상향등범칙금", "도로교통법상향등", "야간눈부심사고"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "오토데일리 / 불스원 블로그",
    desc: "상향등 눈부심으로 인한 야간 사고 위험과 도로교통법상 상향등 사용 규정을 정리했다. 상향등을 켜야 할 때와 반드시 하향등으로 전환해야 할 때, 위반 시 범칙금까지 실제 자료를 바탕으로 다뤘다."
  },
  {
    slug: "vehicle-inspection-fine-2026",
    title: "\"깜빡했다간 과태료 폭탄\"… 자동차 정기검사 안 받으면 벌어지는 일",
    date: "2026-08-01",
    image: "vehicle_inspection_lane.webp",
    categories: ["news"],
    tags: ["자동차정기검사", "정기검사과태료", "자동차검사미이행", "운행정지명령", "자동차365"],
    badge: "POLICY UPDATE",
    badgeClass: "cat-sales",
    source: "찾기쉬운 생활법령정보 / KB국민카드 생각",
    desc: "자동차 정기검사 유효기간을 넘기면 지연 기간별로 과태료가 계단식으로 불어난다. 30일 이내 4만원, 30~114일은 3일마다 2만원씩 추가, 115일 이상은 상한액 60만원까지 부과되며, 1년 이상 방치하면 운행정지명령·번호판 영치·직권말소까지 이어질 수 있다는 점을 정리했다."
  },
  {
    slug: "car-battery-jump-start-guide-2026",
    title: "\"보험 부르기 전에 5분만\"… 방전된 배터리, 점프 스타트로 직접 살리는 법",
    date: "2026-08-01",
    image: "car_battery_jumper_cable_clips.webp",
    categories: ["news"],
    tags: ["배터리방전", "점프스타트", "점프케이블연결순서", "자동차배터리교체", "긴급출동서비스"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "파이낸셜뉴스 / 겟차",
    desc: "긴급출동 서비스 호출의 41%가 배터리 방전일 만큼 흔한 고장이다. 점프 케이블 연결 순서와 극성을 반대로 연결했을 때의 위험, AGM·스탑앤고 배터리 주의사항까지 직접 점프 스타트하는 법을 정리했다."
  },
  {
    slug: "window-tint-regulation-guide-2026",
    title: "\"이 정도만 넘어도 불법\"… 자동차 썬팅, 어디까지 가능할까",
    date: "2026-08-01",
    image: "window_tint_car_side.webp",
    categories: ["news"],
    tags: ["자동차썬팅규제", "썬팅투과율기준", "창유리가시광선투과율", "선팅과태료", "도로교통법시행령제28조"],
    badge: "POLICY UPDATE",
    badgeClass: "cat-sales",
    source: "서울신문 / 찾기쉬운 생활법령정보",
    desc: "자동차 앞유리·앞좌석 창유리 썬팅의 실제 법적 투과율 기준과 위반 시 과태료, 짙은 선팅이 사고 책임으로 이어진 실제 판례까지 정리했다."
  },
  {
    slug: "school-zone-speed-fine-2026",
    title: "\"몰랐다고 봐주지 않는다\"… 스쿨존 과태료, 얼마나 나올까",
    date: "2026-08-01",
    image: "schoolzone_sign_30kmh.webp",
    categories: ["news"],
    tags: ["스쿨존과태료", "어린이보호구역범칙금", "민식이법", "스쿨존속도위반", "어린이보호구역신호위반"],
    badge: "POLICY UPDATE",
    badgeClass: "cat-sales",
    source: "후굿닷컴 / 헬프유 자동차 이야기",
    desc: "어린이보호구역(스쿨존) 속도위반·신호위반 과태료와 범칙금을 구간별로 정리했다. 민식이법 형사처벌 기준과 가중처벌 시간대까지, 실제 수치로 확인한다."
  },
  {
    slug: "dashcam-battery-drain-management-2026",
    title: "\"주차만 했는데 배터리가 방전됐다\"… 블랙박스 상시녹화, 이렇게 관리하세요",
    date: "2026-08-01",
    image: "dashcam_windshield_mount_recording.webp",
    categories: ["news"],
    tags: ["블랙박스배터리방전", "상시녹화", "저전압차단", "보조배터리", "배터리방전예방"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "SBS 뉴스 / 경향신문",
    desc: "블랙박스 상시녹화가 배터리를 소모하는 원리와 실제 긴급출동 통계, 저전압 차단·보조배터리 등 실질적인 방전 예방법을 정리했다."
  },
  {
    slug: "brake-pad-wear-warning-signs-2026",
    title: "\"끼익 소리 나면 이미 늦었다\"… 브레이크 패드 마모, 이 신호부터 확인하세요",
    date: "2026-08-01",
    image: "brake_pad_wear_indicator_closeup.webp",
    categories: ["news"],
    tags: ["브레이크패드마모", "브레이크패드교체시기", "웨어인디케이터", "브레이크소음", "디스크손상"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "겟차 / 킥스사이다",
    desc: "브레이크 웨어 인디케이터가 내는 끼익 소리는 패드 두께가 이미 약 2~3mm까지 닳았을 때 나는 경고음으로, 들리는 순간 이미 안전 마진이 소진된 상태다. 패드 마모 한계, 평균 교체 주기, 방치 시 디스크 손상으로 이어지는 이유까지 정리했다."
  },
  {
    slug: "tpms-warning-light-guide-2026",
    title: "\"타이어에 바람 빠진 걸 몰랐다\"… TPMS 경고등 켜졌을 때 진짜 해야 할 일",
    date: "2026-08-01",
    image: "tpms_warning_light_dashboard.webp",
    categories: ["news"],
    tags: ["TPMS경고등", "타이어공기압경고등", "타이어공기압점검", "타이어공기압부족", "TPMS대처법"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "Fox News / 삼성화재 다이렉트",
    desc: "TPMS 경고등이 켜졌는데도 그냥 운전을 계속하는 사람이 열에 한 명꼴이라는 조사 결과가 있다. TPMS가 공기압 부족을 감지하는 원리, 국내 장착 의무화 시점, 경고등이 켜졌을 때 순서대로 해야 할 대처법을 실제 통계와 함께 정리했다."
  },
  {
    slug: "tire-tread-wear-limit-summer-heat-2026",
    title: "\"기온 1도 오를 때마다 사고 2.84건\"… 폭염 속 타이어 마모 한계선, 지금 확인해야 하는 이유",
    date: "2026-07-31",
    image: "tire_tread_wear_indicator.webp",
    categories: ["news"],
    tags: ["타이어마모한계선", "타이어교체시기", "타이어파열", "폭염타이어", "트레드웨어인디케이터"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "아시아경제 / 겟차",
    desc: "폭염철 타이어 파열 사고가 급증하는 이유와 타이어 마모 한계선 확인법을 정리했다. 기온 상승과 사고율의 상관관계, 트레드웨어 인디케이터·동전 테스트로 직접 점검하는 방법까지 다뤘다."
  },
  {
    slug: "tesla-model-y-2026-review",
    title: "\"국내 월간 판매 1위\"… 테슬라 모델Y 2026년형, 가격과 제원 총정리",
    date: "2026-07-30",
    image: "tesla_modely_juniper_front.webp",
    categories: ["electric", "import"],
    tags: ["테슬라모델Y", "모델Y가격", "모델Y주니퍼", "모델Y제원", "모델Y판매량"],
    badge: "EV SUV",
    badgeClass: "cat-sales",
    source: "바닐라하이 / CAR INFO",
    desc: "테슬라 모델Y 2026년형의 국내 가격과 제원을 정리했다. 프리미엄 RWD부터 L AWD까지 트림별 가격, 주행거리, 배터리 용량과 국내 월간 판매 1위 배경까지 다뤘다."
  },
  {
    slug: "engine-oil-change-interval-guide-2026",
    title: "\"하이브리드라고 다 똑같지 않다\"… 엔진오일 교환주기, 차종별로 이렇게 다르다",
    date: "2026-07-30",
    image: "engine_oil_pouring.webp",
    categories: ["news"],
    tags: ["엔진오일교환주기", "가솔린엔진오일", "디젤엔진오일", "하이브리드엔진오일", "엔진오일교체시기"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "겟차 / SEEMS INFO",
    desc: "가솔린·디젤·하이브리드 차량의 엔진오일 교환주기를 비교했다. 차종별 권장 주기와 이유, 놓치기 쉬운 하이브리드 오일 관리 포인트까지 정리했다."
  },
  {
    slug: "kia-sportage-6th-gen-rumor-2027",
    title: "\"가솔린 완전히 버린다\"… 기아 스포티지 6세대, 2027년 하이브리드 올인",
    date: "2026-07-30",
    image: "sportage_nq5_front.webp",
    categories: ["news", "domestic"],
    tags: ["스포티지풀체인지", "스포티지6세대", "스포티지NQ6", "스포티지하이브리드", "스포티지출시일"],
    badge: "RUMOR",
    badgeClass: "cat-hyundai",
    source: "뉴스와 / 클리앙",
    desc: "기아 스포티지 완전변경(NQ6)이 2027년 3분기 출시를 목표로 개발 중이다. 가솔린·디젤·LPG를 없애고 HEV·PHEV로 단순화하는 파워트레인 전략과 예상 정보를 정리했다."
  },
  {
    slug: "santa-fe-facelift-2026",
    title: "\"이러면 쏘렌토 안 타죠\"… 싼타페 페이스리프트, 사실상 풀체인지급 변신",
    date: "2026-07-30",
    image: "santa_fe_mx5_front.webp",
    categories: ["news", "domestic"],
    tags: ["싼타페페이스리프트", "싼타페5세대", "싼타페디자인변경", "싼타페출시일", "싼타페EREV"],
    badge: "RUMOR",
    badgeClass: "cat-hyundai",
    source: "글로벌모터스 / 오토스파이넷",
    desc: "현대차 싼타페 페이스리프트가 스파이샷으로 포착됐다. 호불호 컸던 H 램프 전면 수정, 플레오스 커넥트, EREV 파워트레인 추가설까지 예상 정보를 정리했다."
  },
  {
    slug: "driving-license-renewal-guide-2026",
    title: "\"생일 기준으로 바뀌었다\"… 2026 운전면허증 갱신, 놓치면 과태료",
    date: "2026-07-30",
    image: "driving_license_exam_office.jpg",
    categories: ["news"],
    tags: ["운전면허증갱신", "운전면허갱신기간", "운전면허적성검사", "운전면허갱신준비물", "운전면허과태료"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "도로교통공단 안전운전 통합민원 / FAST1",
    desc: "2026년 운전면허증 갱신 방법과 기간을 정리했다. 생일 전후 6개월로 바뀐 갱신 기준, 1종·2종 차이, 준비물, 기한을 넘기면 생기는 불이익까지 다뤘다."
  },
  {
    slug: "hyundai-casper-2026my-price-2026",
    title: "\"옵션 값 안 내도 다 있다\"… 2026년형 캐스퍼, 최대 91만원 올랐지만 그럴 만한 이유",
    date: "2026-07-30",
    image: "hyundai_casper_2026.webp",
    categories: ["domestic"],
    tags: ["2026년형캐스퍼", "캐스퍼가격", "캐스퍼일렉트릭가격", "캐스퍼옵션", "현대경형SUV"],
    badge: "PRICE UPDATE",
    badgeClass: "cat-hyundai",
    source: "다나와 자동차 / 현대자동차그룹",
    desc: "현대차가 2026년형 캐스퍼·캐스퍼 일렉트릭을 출시했다. 최대 91만원 오른 가격과 트림별 기본 사양 강화 내용, 풀옵션 가격까지 정리했다."
  },
  {
    slug: "tesla-fsd-korea-launch-safety-2026",
    title: "\"한국 도로가 테스트베드\"… 테슬라 FSD 라이트 상륙, 안전성 논란 확산",
    date: "2026-07-30",
    image: "tesla_modely_juniper_interior.webp",
    categories: ["electric", "news"],
    tags: ["테슬라FSD", "FSD라이트한국", "테슬라자율주행안전성", "FSD한국출시", "테슬라FSD논란"],
    badge: "SAFETY ISSUE",
    badgeClass: "cat-sales",
    source: "지피코리아 / 오토트리뷴 / MS투데이",
    desc: "테슬라의 감독형 자율주행 'FSD 라이트'가 한국에 상륙했다. 미국 외 세계 최초 도입 배경과 사고 책임 소재, 안전성 논란까지 정리했다."
  },
  {
    slug: "audi-q9-flagship-suv-2026",
    title: "\"아우디 역사상 가장 큰 SUV\"… Q9, 전장 5,310mm 초대형 플래그십 공개",
    date: "2026-07-29",
    image: "audi_q9_front.webp",
    categories: ["import", "news"],
    tags: ["아우디Q9", "Q9출시", "Q9가격", "Q9제원", "아우디대형SUV"],
    badge: "FLAGSHIP SUV",
    badgeClass: "cat-sales",
    source: "더드라이브 / 오토헤럴드 / 카랩 블로그",
    desc: "아우디의 역대급 플래그십 SUV 'Q9'이 공개됐다. 전장 5,310mm의 초대형 차체, 시장별 파워트레인 구성, 미국 가격과 국내 출시 전망까지 정리했다."
  },
  {
    slug: "byd-racco-japan-kei-car-2026",
    title: "\"1900만원대, 레이보다 낫다\"… BYD 라코, 일본 경차 텃밭에 던진 도전장",
    date: "2026-07-29",
    image: "byd_racco_front.webp",
    categories: ["electric", "import"],
    tags: ["BYD라코", "BYD RACCO", "일본경차전기차", "BYD경형EV", "라코가격"],
    badge: "JAPAN EXCLUSIVE",
    badgeClass: "cat-sales",
    source: "뉴스와 / BYD코리아 / 스타뉴스",
    desc: "BYD가 일본 전용 첫 경형 전기차 '라코'를 정식 출시했다. 외국 브랜드 최초의 일본 케이카 도전, 자동 슬라이딩 도어, 배터리·가격 정보까지 정리했다."
  },
  {
    slug: "genesis-gv80-hybrid-2026",
    title: "\"전기차만 만들겠다더니\"… 제네시스 GV80 하이브리드, 9월 출시로 선언 뒤집었다",
    date: "2026-07-29",
    image: "genesis_gv80_front.webp",
    categories: ["news", "domestic"],
    tags: ["제네시스GV80하이브리드", "GV80출시일", "제네시스하이브리드전략", "GV80연비", "제네시스전기차전략수정"],
    badge: "STRATEGY SHIFT",
    badgeClass: "cat-genesis",
    source: "토픽트리 / 유카포스트 / 오토포커스",
    desc: "제네시스가 2026년 9월 GV80 하이브리드를 출시한다. 2025년 선언한 전 차종 전기차 전환 계획을 뒤집은 배경과 2.5T 하이브리드 파워트레인, 향후 전동화 전략까지 정리했다."
  },
  {
    slug: "kia-ev5-review-2026",
    title: "\"가족 모두를 매료시키는 5할 타자\"… 기아 EV5 시승기, 4천만원대 전기 SUV",
    date: "2026-07-29",
    image: "kia_ev5_front.webp",
    categories: ["electric", "domestic"],
    tags: ["기아EV5", "EV5가격", "EV5시승기", "EV5제원", "준중형전기SUV"],
    badge: "EV SUV",
    badgeClass: "cat-hyundai",
    source: "현대자동차그룹",
    desc: "기아 EV5의 국내 가격과 제원, 시승 평가를 정리했다. 에어·어스·GT-Line 3개 트림, 스탠다드·롱레인지 배터리, 서울시 보조금 적용 시 3,400만원대 실구매가까지 다뤘다."
  },
  {
    slug: "byd-sealion6-dmi-review-2026",
    title: "\"3,750만원이면 쏘렌토 대신\"… BYD 씨라이언6 DM-i 시승기",
    date: "2026-07-29",
    image: "byd_sealion6_dmi_front.webp",
    categories: ["reviews", "import"],
    tags: ["BYD씨라이언6", "씨라이언6DMi", "BYD코리아", "BYD PHEV", "수입PHEVSUV"],
    badge: "TEST DRIVE",
    badgeClass: "cat-hyundai",
    source: "다나와 자동차",
    desc: "BYD코리아의 첫 PHEV 씨라이언6 DM-i 시승기를 정리했다. 3,750만원 가격, EV 주행거리 70km, 복합연비 15.2km/L, 세이브 모드 등 실제 주행 인상까지 다뤘다."
  },
  {
    slug: "zero-to-hundred-3sec-sportscars-top5-2026",
    title: "\"제로백 3초대, 심장이 쫄깃하다\" — 국내 구매 가능 고성능 스포츠카 5선",
    date: "2026-07-29",
    image: "mclaren_artura.webp",
    categories: ["news", "import"],
    tags: ["제로백3초대", "고성능스포츠카", "수입스포츠카", "스포츠카5선", "슈퍼카가격"],
    badge: "TOP 5",
    badgeClass: "cat-sales",
    source: "탑라이더 / 이코노믹데일리 / 에이빙 / 국제뉴스",
    desc: "국내에서 실제 구매 가능한 제로백 3초대 고성능 스포츠카 5종을 정리했다. 맥라렌 아투라, 람보르기니 우라칸 테크니카, AMG GT 63 S, 포르쉐 911 카레라 GTS, 벤틀리 컨티넨탈 GT S까지 가격과 성능을 비교했다."
  },
  {
    slug: "bmw-x7-full-change-preview-2027",
    title: "\"지금 살까, 2027까지 기다릴까\"… BMW X7 완전변경, 노이에 클라세로 승부수",
    date: "2026-07-29",
    image: "bmw_x7_front.webp",
    categories: ["import", "news"],
    tags: ["BMWX7풀체인지", "BMWX7완전변경", "노이에클라세", "iX7", "BMW대형SUV"],
    badge: "FULL CHANGE",
    badgeClass: "cat-sales",
    source: "오토트리뷴 / 뉴스와",
    desc: "BMW X7 완전변경 소식을 정리했다. 2027년 공개 예정인 신형은 노이에 클라세 디자인 언어와 확대된 키드니 그릴, 순수 전기 iX7까지 아우르는 파격적인 변화를 예고했다."
  },
  {
    slug: "hyundai-ioniq9-review-2026",
    title: "\"핫해치급 가속에 세단 승차감\"… 아이오닉9, 532km 주행거리의 3열 전기 SUV",
    date: "2026-07-29",
    image: "ioniq9_front.webp",
    categories: ["electric", "domestic"],
    tags: ["아이오닉9", "아이오닉9가격", "아이오닉9제원", "3열전기SUV", "아이오닉9캘리그래피"],
    badge: "FLAGSHIP EV",
    badgeClass: "cat-hyundai",
    source: "오토인리 / 다나와 자동차",
    desc: "현대 아이오닉9의 국내 가격과 제원, 시승 평가를 취합했다. 최대 532km 주행거리, 3130mm 휠베이스의 동급 최대 실내공간, 하이드로 부싱 서스펜션까지 정리했다."
  },
  {
    slug: "lexus-es300h-2026-review",
    title: "\"한국에서 10만대 팔린 이유\"… 렉서스 ES300h 2026년형 시승기",
    date: "2026-07-28",
    image: "lexus_es300h_front.webp",
    categories: ["reviews", "import"],
    tags: ["렉서스ES300h", "ES300h시승기", "ES300h가격", "렉서스하이브리드", "준대형세단"],
    badge: "TEST DRIVE",
    badgeClass: "cat-hyundai",
    source: "탑라이더",
    desc: "렉서스 ES300h 2026년형 시승기를 정리했다. 익스클루시브·럭셔리+ 2개 트림 가격, D-4S 하이브리드 시스템 218마력, 복합연비 17.2km/L, 국내 10만대 판매 비결까지 다뤘다."
  },
  {
    slug: "tesla-model3-highland-review-2026",
    title: "\"공기저항계수 역대 최저\"… 테슬라 모델3 하이랜드, RWD로 타봐도 만족스러운 이유",
    date: "2026-07-28",
    image: "tesla_model3_highland_front.webp",
    categories: ["electric", "import"],
    tags: ["테슬라모델3", "모델3하이랜드", "테슬라RWD", "모델3롱레인지", "전기세단"],
    badge: "EV SEDAN",
    badgeClass: "cat-sales",
    source: "겟차 / 클리앙",
    desc: "테슬라 모델3 하이랜드의 국내외 정보를 취합했다. 공력계수 0.219Cd, 후석 8인치 스크린, 개선된 승차감과 480km 이상 주행거리, RWD 시승 반응까지 정리했다."
  },
  {
    slug: "genesis-gv90-neolun-preview-2026",
    title: "\"마이바흐는 이제 제네시스 아래\"… GV90, 9월 9일 공개 확정",
    date: "2026-07-28",
    image: "genesis_gv90_neolun_front.webp",
    categories: ["electric", "domestic"],
    tags: ["제네시스GV90", "GV90출시", "네오룬콘셉트", "제네시스플래그십SUV", "GV90가격"],
    badge: "FLAGSHIP EV",
    badgeClass: "cat-genesis",
    source: "나무위키 / 아시아타임 / The Korean Car Blog",
    desc: "제네시스의 대형 플래그십 전기 SUV 'GV90'이 9월 9일 글로벌 공개를 확정했다. 네오룬 콘셉트로 먼저 공개된 디자인 방향과 예상 제원, 국내 출시 일정과 가격 전망까지 정리했다."
  },
  {
    slug: "kimbujang-drama-polestar-2026",
    title: "\"김부장이 타는 그 차\"… 넷플릭스 세계 1위 드라마 속 폴스타, 실제로 얼마?",
    date: "2026-07-28",
    image: "polestar3_front.webp",
    categories: ["news"],
    tags: ["김부장차종", "김부장폴스타", "폴스타3협찬", "폴스타4협찬", "넷플릭스김부장"],
    badge: "DRAMA × AUTO",
    badgeClass: "cat-sales",
    source: "네이트뉴스 / 스포츠월드",
    desc: "SBS 드라마 '김부장'이 넷플릭스 비영어권 3주 연속 세계 1위를 기록하며 극 중 협찬 차량 폴스타3·폴스타4도 함께 화제를 모았다. 드라마 속 차량과 실제 국내 가격·제원을 정리했다."
  },
  {
    slug: "hyundai-tucson-5th-gen-rumor-2027",
    title: "\"이러면 스포티지 누가 사나\"… 5세대 투싼 완전변경 예상도 화제, 아직은 루머",
    date: "2026-07-28",
    image: "tucson_2027_render_front.webp",
    categories: ["news", "domestic"],
    tags: ["투싼풀체인지", "5세대투싼", "투싼NX5", "투싼2027", "투싼루머"],
    badge: "RUMOR",
    badgeClass: "cat-hyundai",
    source: "더드라이브 / AutoData Hub / 오토야 인테리어(유튜브)",
    desc: "2027년 출시가 예상되는 5세대 투싼 완전변경 예상도가 화제다. 현대차 공식 발표가 아닌 스파이샷·렌더링 기반 업계 루머라는 점을 전제로, 예상 디자인과 파워트레인, 가격 전망을 정리했다."
  },
  {
    slug: "polestar-4-2026my-korea",
    title: "\"미국에서는 마지막 모델\"… 2026년형 폴스타4, 국내는 가격 동결하고 상품성 강화",
    date: "2026-07-28",
    image: "polestar4_front.webp",
    categories: ["electric", "import"],
    tags: ["폴스타4", "폴스타2026년형", "폴스타전기SUV쿠페", "폴스타국내출시", "수입전기차"],
    badge: "EV UPDATE",
    badgeClass: "cat-sales",
    source: "다나와 자동차 / 오토뷰 / Autoblog",
    desc: "폴스타코리아가 2026년형 폴스타4를 국내 출시했다. 가격은 동결하고 옵션은 강화한 국내 소식과 544마력 성능, 해외 시승 평가, 미국 시장 철수 이슈까지 취합해 정리했다."
  },
  {
    slug: "polestar-3-korea-launch-2026",
    title: "\"드라이브 모드도 화면 세 번 눌러야\"… 폴스타3 한국 상륙, 7790만원의 이유",
    date: "2026-07-28",
    image: "polestar3_front.webp",
    categories: ["electric", "import"],
    tags: ["폴스타3", "폴스타전기SUV", "폴스타국내출시", "전기플래그십SUV", "수입전기차"],
    badge: "FLAGSHIP EV",
    badgeClass: "cat-sales",
    source: "탑라이더 / Motoring Research",
    desc: "폴스타의 플래그십 전기 SUV 폴스타3가 한국에 상륙했다. 전 세계 최저가로 책정된 7790만원부터의 가격, 680마력 성능, 국내외 시승 평가까지 취합해 정리했다."
  },
  {
    slug: "toyota-sequoia-2027-review",
    title: "\"화면은 커졌지만 승차감은 그대로\"… 2027 토요타 세쿼이아, 트레일헌터로 던진 승부수",
    date: "2026-07-28",
    image: "toyota_sequoia_2027_front.webp",
    categories: ["import", "news"],
    tags: ["토요타세쿼이아", "세쿼이아트레일헌터", "세쿼이아페이스리프트", "대형SUV", "i포스맥스"],
    badge: "MODEL UPDATE",
    badgeClass: "cat-sales",
    source: "Toyota USA Newsroom / AutoGuide.com",
    desc: "토요타가 대형 SUV 세쿼이아의 2027년형을 공개했다. 새로워진 외관과 14인치 인포테인먼트, 오프로드 특화 트레일헌터 트림까지 국내외 정보를 취합해 정리했다."
  },
  {
    slug: "maserati-grecale-trofeo-review-2026",
    title: "\"생각보다 얌전하다, 한계까지는\"… 마세라티 그레칼레 트로페오, 네튜노 V6 523마력 시승기 총정리",
    date: "2026-07-27",
    image: "maserati_grecale_trofeo_main.webp",
    categories: ["reviews", "import"],
    tags: ["마세라티그레칼레", "그레칼레트로페오", "네튜노V6", "마세라티SUV", "수입차리뷰"],
    badge: "PERFORMANCE SUV",
    badgeClass: "cat-sales",
    source: "에너지경제(EKN) / duPont REGISTRY / Forbes",
    desc: "마세라티 그레칼레 트로페오의 국내외 시승기를 취합했다. MC20에서 가져온 네튜노 V6 523마력 파워트레인, 주행 인상, 실내 마감, 국내외 가격까지 정리했다."
  },
  {
    slug: "recall-byd-benz-hyundai-volvo-jlr-july-2026",
    title: "\"내 차도 포함됐나?\"… BYD·벤츠·현대차 등 6개사 14만 6,505대 리콜",
    date: "2026-07-27",
    image: "hyundai_tucson_recall.webp",
    categories: ["news", "domestic", "import"],
    tags: ["자동차리콜2026", "국토부리콜", "BYD리콜", "벤츠리콜", "현대차투싼리콜"],
    badge: "RECALL",
    badgeClass: "cat-sales",
    source: "헤럴드경제 / MBC뉴스",
    desc: "국토교통부가 BYD·벤츠·스텔란티스·재규어랜드로버·현대차·볼보 등 6개사 38개 차종 14만 6,505대의 제작 결함을 확인해 리콜을 진행한다. 차종별 결함 내용과 조회 방법을 정리했다."
  },
  {
    slug: "genesis-gv60-magma-nurburgring-track-taxi-2026",
    title: "\"택시인데 시속 200km\"… 제네시스 GV60 마그마, 뉘르부르크링 트랙택시 합류",
    date: "2026-07-27",
    image: "genesis_gv60_magma_interior1.webp",
    categories: ["news", "domestic", "electric"],
    tags: ["GV60마그마", "뉘르부르크링트랙택시", "제네시스트랙택시", "GV60마그마제원", "노르트슐라이페"],
    badge: "TRACK TAXI",
    badgeClass: "cat-genesis",
    source: "뉴스와이어 / Motoring Research",
    desc: "제네시스 GV60 마그마가 독일 뉘르부르크링 노르트슐라이페의 유료 트랙택시 프로그램에 투입됐다. 듀얼모터 650마력 제원과 체험 방법, 요금까지 정리했다."
  },
  {
    slug: "genesis-luxury-pickup-truck-review-2026",
    title: "\"벤츠도 실패한 시장\"… 제네시스, 럭셔리 픽업트럭 출시 검토 중",
    date: "2026-07-27",
    image: "genesis_pickup_render_carscoops1.webp",
    categories: ["news", "domestic"],
    tags: ["제네시스픽업트럭", "제네시스픽업검토", "제네시스프레임바디", "제네시스EREV픽업", "럭셔리픽업트럭"],
    badge: "UNDER REVIEW",
    badgeClass: "cat-genesis",
    source: "뉴스와 / Carscoops",
    desc: "제네시스가 브랜드 최초의 럭셔리 픽업트럭 출시를 검토하고 있다. 현대차 신형 프레임바디 플랫폼, 하이브리드·EREV 파워트레인 전망, 벤츠 X클래스 실패 사례와 시장 전략까지 정리했다."
  },
  {
    slug: "kgm-torres-facelift-price-spec-2026",
    title: "\"터치 대신 다이얼로 바꿨다\"… KGM 뉴 토레스 페이스리프트 가격·제원 총정리",
    date: "2026-07-27",
    image: "kgm_new_torres_showroom.webp",
    categories: ["news", "domestic"],
    tags: ["KGM토레스페이스리프트", "뉴토레스가격", "토레스하이브리드가격", "토레스터레인모드", "토레스다이얼"],
    badge: "FACELIFT",
    badgeClass: "cat-sales",
    source: "뉴스1 / 오토스파이넷",
    desc: "KGM이 뉴 토레스 페이스리프트를 출시했다. 가솔린 2,905만원·하이브리드 3,205만원부터 시작하는 가격표와 8단 변속기로 개선된 파워트레인, 터레인 모드, 터치 조작을 다이얼로 바꾼 실내 변화까지 정리했다."
  },
  {
    slug: "kia-ev4-price-spec-review-2026",
    title: "\"이 가격에 533km가 가능하다고?\"… 기아 EV4 가격·제원·해외 평가 총정리",
    date: "2026-07-27",
    image: "kia_ev4_main.webp",
    categories: ["news", "domestic", "electric"],
    tags: ["기아EV4", "EV4가격", "EV4주행거리", "EV4GT", "EV4시승평가"],
    badge: "EV SEDAN",
    badgeClass: "cat-sales",
    source: "Electrifying / 기아 공식 홈페이지",
    desc: "기아의 준중형 전기 세단 EV4를 총정리했다. 스탠다드·롱레인지 트림별 국내 가격과 주행거리, 292마력 EV4 GT 고성능 모델, 해외 시승 평가까지 정리했다."
  },
  {
    slug: "hyundai-kona-full-change-sx3-2027",
    title: "\"이번엔 진심이다\"… 코나 풀체인지 총정리, 178마력 사륜 하이브리드까지",
    date: "2026-07-26",
    image: "hyundai_kona.webp",
    categories: ["news", "domestic"],
    tags: ["코나풀체인지", "코나3세대", "코나SX3", "코나신형출시일", "코나사륜하이브리드"],
    badge: "PROJECT SX3",
    badgeClass: "cat-sales",
    source: "뉴스와 / 오토뷰",
    desc: "현대차가 코나 부분변경을 건너뛰고 3세대 완전변경(SX3)으로 직행한다. 셀토스를 겨냥한 배경과 크레이터 콘셉트카에서 영감받은 디자인, 178마력 e-AWD 하이브리드, 예상 출시일까지 정리했다."
  },
  {
    slug: "kia-pv5-passenger-autocar-award-price-2026",
    title: "\"영국에서 난리 났다\"… 기아 PV5 패신저, 오토카 '최고의 대형차' 수상 — 가격 4,709만원부터",
    date: "2026-07-26",
    image: "kia_pv5_passenger_main.webp",
    categories: ["news", "domestic", "electric"],
    tags: ["기아PV5패신저", "PV5패신저가격", "PV5오토카어워즈", "PV5제원", "PV5패신저주행거리"],
    badge: "EV MPV",
    badgeClass: "cat-sales",
    source: "The Korea Times / 디지털데일리",
    desc: "기아 PV5 패신저가 영국 오토카 어워즈에서 '최고의 대형차'로 선정됐다. 세계 올해의 밴 등 글로벌 수상 이력과 함께, E-GMP.S 플랫폼 제원, 국내 트림별 가격, 5인승 시트 구성까지 총정리했다."
  },
  {
    slug: "hyundai-ioniq3-price-spec-korea-launch-2026",
    title: "\"롱레인지가 힘은 더 약하다\"… 현대 올 뉴 아이오닉 3 가격·제원 총정리, 국내 출시는 언제",
    date: "2026-07-26",
    image: "ioniq3_main.webp",
    categories: ["news", "domestic", "electric"],
    tags: ["아이오닉3", "아이오닉3가격", "아이오닉3제원", "아이오닉3국내출시", "올뉴아이오닉3"],
    badge: "EV HATCHBACK",
    badgeClass: "cat-hyundai",
    source: "뉴스와 / 토픽트리",
    desc: "아이오닉 브랜드 첫 소형 전기 해치백 올 뉴 아이오닉 3를 총정리했다. 유럽 출시 가격과 배터리별 주행거리, 플레오스 커넥트 실내, 국내 출시 시점 전망까지 정리했다."
  },
  {
    slug: "hyundai-palisade-full-change-price-review-2026",
    title: "현대 팰리세이드 풀체인지 가격·제원·시승기 총정리 — 가솔린 vs 하이브리드",
    date: "2026-07-26",
    image: "palisade_full_change_main.webp",
    categories: ["news", "domestic", "reviews"],
    tags: ["팰리세이드풀체인지", "디올뉴팰리세이드", "팰리세이드가격표", "팰리세이드하이브리드시승기", "팰리세이드가솔린하이브리드비교"],
    badge: "TEST DRIVE",
    badgeClass: "cat-hyundai",
    source: "Edmunds / MotorWeek",
    desc: "2세대 완전변경된 디 올 뉴 팰리세이드를 총정리했다. 가솔린·하이브리드 트림별 가격표, 커진 차체와 실내 공간, 국내외 시승기 평가와 하이브리드 판매 비중 80%가 넘는 이유까지 정리했다."
  },
  {
    slug: "kgm-musso-ev-pickup-price-review-2026",
    title: "KGM 무쏘 EV 가격·제원·시승 총정리 — 화물차 등록으로 실구매가 3천만원대",
    date: "2026-07-26",
    image: "kgm_musso_ev_main.webp",
    categories: ["news", "domestic", "electric"],
    tags: ["KGM무쏘EV", "무쏘EV가격", "전기픽업트럭", "무쏘EV보조금", "무쏘EV시승기"],
    badge: "EV PICKUP",
    badgeClass: "cat-sales",
    source: "뉴스와 / 카가이",
    desc: "국내 최초 전기 픽업트럭 KGM 무쏘 EV를 총정리했다. 트림별 가격과 화물차 등록으로 받는 보조금, 2WD·AWD 제원과 적재량·견인력, 국내외 시승기 평가까지 정리했다."
  },
  {
    slug: "zeekr-7x-korea-price-spec-2026",
    title: "지커 7X 가격·제원 총정리 — 라이다 빠진 국내 사양과 보조금 미지급 이유",
    date: "2026-07-26",
    image: "zeekr_7x_main.webp",
    categories: ["news", "import", "electric"],
    tags: ["지커7X", "지커7X가격", "지커7X제원", "지커7X보조금", "지커7X사전계약"],
    badge: "EV SUV",
    badgeClass: "cat-sales",
    source: "뉴스와 / 이데일리",
    desc: "지리(Geely) 산하 지커의 첫 한국 출시 모델 7X를 총정리했다. 트림별 가격과 주행거리, 글로벌 사양에서 빠진 라이다·엔비디아 토르, 보조금 없이도 사전계약 1000대를 넘긴 이유까지 정리했다."
  },
  {
    slug: "budget-cars-20-million-won-2026",
    title: "2000만원대 추천 차량 5선 — 경차부터 소형 SUV·전기차까지 예산별 총정리",
    date: "2026-07-25",
    image: "hyundai_casper_2026.webp",
    categories: ["news", "domestic"],
    tags: ["2000만원대추천차량", "2000만원대신차추천", "2000만원대SUV추천", "2000만원대세단", "가성비신차추천2026"],
    badge: "BUYING GUIDE",
    badgeClass: "cat-sales",
    source: "현대자동차 공식 홈페이지 / 차프라이스",
    desc: "2000만원대 예산으로 살 수 있는 신차 5종을 총정리했다. 캐스퍼, 아반떼, 베뉴, 코나, 캐스퍼 일렉트릭까지 경차·준중형·소형 SUV·전기차를 트림별 가격과 함께 비교했다."
  },
  {
    slug: "hipass-unpaid-toll-check-autopay-guide",
    title: "하이패스 미납요금 조회 방법과 자동납부 신청 — 방치하면 최대 10배 가산금",
    date: "2026-07-25",
    image: "seoul_tollgate_hipass.jpg",
    categories: ["news"],
    tags: ["하이패스미납요금조회", "하이패스자동납부신청", "고속도로통행료미납조회", "하이패스미납가산금", "하이패스미납요금납부방법"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "하이패스 홈페이지 / 소비자가만드는신문",
    desc: "하이패스 미납요금은 홈페이지·앱·콜센터에서 셀프로 조회할 수 있다. 후불 하이패스카드 자동납부 신청 방법과, 방치했을 때 최대 10배까지 붙는 가산금·강제징수 절차까지 정리했다."
  },
  {
    slug: "drowsy-driving-coffee-nap-checklist",
    title: "졸음운전 대처법, 커피보다 효과적인 '커피 낮잠' — 장거리 운전 전 체크리스트",
    date: "2026-07-25",
    image: "drowsy_driving_nod_off.webp",
    categories: ["news"],
    tags: ["졸음운전대처법", "커피낮잠", "졸음운전예방법", "장거리운전체크리스트", "파워냅운전"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "더드라이브 / 뉴스와",
    desc: "졸음운전에 커피만 마시고 버티면 오히려 위험하다. 카페인이 작동하기까지 20~30분 걸리는 원리를 이용한 '커피 낮잠' 요령부터 장거리 운전 전 꼭 확인할 체크리스트까지 정리했다."
  },
  {
    slug: "no-signal-intersection-priority-guide",
    title: "신호 없는 교차로 우선순위 완전정리 — 초보운전자가 가장 헷갈리는 상황 5가지",
    date: "2026-07-25",
    image: "korea_roundabout.webp",
    categories: ["news"],
    tags: ["신호없는교차로우선순위", "교차로통행우선권", "우측차량우선", "회전교차로통행방법", "점멸신호서행"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "헤드라인제주 / 브런치",
    desc: "신호등 없는 교차로에서 뭐가 우선인지 헷갈린다면 도로교통법 제26조부터 확인해야 한다. 동시 도착, 도로 폭, 좌회전, 회전교차로, 점멸신호까지 초보운전자가 가장 헷갈리는 5가지 상황을 정리했다."
  },
  {
    slug: "first-car-recommendation-top5-2026",
    title: "첫차 추천 TOP 5 — 1,395만원 모닝부터 니로 하이브리드까지 예산별 총정리",
    date: "2026-07-24",
    image: "kia_morning.webp",
    categories: ["news", "domestic"],
    tags: ["첫차추천", "사회초년생첫차", "초보운전첫차추천", "첫차순위", "예산별신차추천"],
    badge: "BUYING GUIDE",
    badgeClass: "cat-sales",
    source: "CAR INFO",
    desc: "사회초년생·초보운전자를 위한 첫차 추천 TOP 5를 예산순으로 정리했다. 기아 모닝, 현대 캐스퍼, 기아 레이, 현대 아반떼, 기아 니로 하이브리드까지 가격·연비·유지비를 비교했다."
  },
  {
    slug: "kia-k8-2027-review",
    title: "기아 K8 가격 3,731만원부터 — 하이브리드 연비 18km/L, 국내외 시승기 총정리",
    date: "2026-07-24",
    image: "kia_k8_2027_front.webp",
    categories: ["domestic", "reviews"],
    tags: ["기아K8가격", "K8시승기", "K8하이브리드연비", "더뉴K8", "준대형세단추천"],
    badge: "TEST DRIVE",
    badgeClass: "cat-hyundai",
    source: "차가치 / 애틀랜타K뉴스",
    desc: "기아 준대형 세단 더 뉴 K8의 27년형 트림별 가격과 파워트레인, 국내외 시승기를 총정리했다. 스타맵 시그니처 라이팅 디자인부터 하이브리드 실연비, 그랜저와의 비교까지 정리했다."
  },
  {
    slug: "parking-brake-vs-foot-brake-hill-stop",
    title: "언덕 정차 시 브레이크, 주차브레이크가 맞을까 풋브레이크가 맞을까 — 초보운전자 필수 상식",
    date: "2026-07-24",
    image: "parking_brake_lever.webp",
    categories: ["news"],
    tags: ["언덕정차브레이크", "주차브레이크풋브레이크차이", "오르막길정차방법", "오토홀드사용법", "브레이크페이드"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "슬기로운 자동차생활 / 금호타이어 블로그",
    desc: "오르막길에서 정차할 때 풋브레이크만 밟고 있으면 위험하다. 오토홀드, 수동변속기 반클러치 요령부터 내리막길 브레이크 페이드 예방까지, 초보운전자가 알아야 할 언덕 정차·출발 브레이크 사용법을 정리했다."
  },
  {
    slug: "ev-summer-heat-range-tips-2026",
    title: "전기차 폭염철 주행거리 17% 뚝 — 항속거리 지키는 습관 5가지",
    date: "2026-07-24",
    image: "ev_charging.jpg",
    categories: ["electric", "news"],
    tags: ["전기차폭염주행거리", "전기차배터리관리", "전기차항속거리", "에어컨프리컨디셔닝", "배터리온도관리"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "스타뉴스 / 블랑루시",
    desc: "섭씨 35도 이상 폭염에 에어컨을 켜고 달리면 전기차 주행거리가 17% 줄어든다. 충전 중 프리컨디셔닝부터 배터리 온도 관리까지, 폭염철 전기차 항속거리를 지키는 습관 5가지를 정리했다."
  },
  {
    slug: "dui-interlock-conditional-license-2026",
    title: "음주운전 방지장치 조건부 면허, 10월 24일 첫 적용 — 대상·비용·처벌 총정리",
    date: "2026-07-24",
    image: "dui_interlock_device_test.webp",
    categories: ["news"],
    tags: ["음주운전방지장치조건부면허", "시동잠금장치", "조건부운전면허", "상습음주운전", "도로교통법개정"],
    badge: "POLICY UPDATE",
    badgeClass: "cat-sales",
    source: "세계일보 / 경향신문",
    desc: "상습 음주운전자가 면허를 재취득할 때 음주운전 방지장치 부착이 의무화되는 조건부 면허 제도의 실제 적용이 10월 24일부터 시작된다. 대상 기준, 장치 작동 방식과 비용, 위반 시 처벌까지 총정리했다."
  },
  {
    slug: "summer-car-discount-2026-07",
    title: "그랜저 300만원·팰리세이드 300만원 할인 — 국산차 5개사 여름휴가철 프로모션 총정리",
    date: "2026-07-24",
    image: "grandeur_official.png",
    categories: ["news", "domestic"],
    tags: ["그랜저할인", "팰리세이드할인", "여름휴가철신차할인", "현대차썸머페스타", "국산차할인"],
    badge: "SUMMER DISCOUNT",
    badgeClass: "cat-sales",
    source: "다나와 자동차 / 인더뉴스",
    desc: "현대차 썸머 페스타로 그랜저·팰리세이드가 최대 300만원 할인된다. 기아·제네시스·KGM·르노코리아까지 국산차 5개사가 동시에 진행 중인 7월 여름휴가철 신차 할인 조건을 총정리했다."
  },
  {
    slug: "gac-e8-phev-2026",
    title: "GAC E8 PHEV 공개 — 순수전기 281km·복합연비 3.98L 세계기록 MPV 총정리",
    date: "2026-07-23",
    image: "gac_e8_phev_main.webp",
    categories: ["import"],
    tags: ["GACE8PHEV", "중국PHEVMPV", "플러그인하이브리드", "GAC트럼프치", "MPV세계기록"],
    badge: "PHEV MPV",
    badgeClass: "cat-sales",
    source: "신랑차(新浪汽车) / IT之家",
    desc: "GAC(광저우자동차)가 신형 E8 PHEV를 공개했다. 순수전기 281km, WLTC 기준 연비 3.98L/100km로 MPV 세계기록을 세운 신형 플러그인 하이브리드의 파워트레인, 실내 공간, 가격을 총정리했다."
  },
  {
    slug: "volvo-es90-korea-launch-2026",
    title: "볼보 ES90 국내 출시 — 706km 전기 플래그십, 글로벌보다 5000만 원 싼 이유",
    date: "2026-07-23",
    image: "volvo_es90_main.webp",
    categories: ["electric", "import"],
    tags: ["볼보ES90", "전기플래그십세단", "볼보국내출시", "800V급속충전", "수입전기차"],
    badge: "FLAGSHIP EV",
    badgeClass: "cat-sales",
    source: "한국경제 / 파이낸셜뉴스",
    desc: "볼보의 순수 전기 플래그십 세단 ES90이 국내 정식 출시했다. 706km 주행거리, 3가지 파워트레인, 800V 급속충전까지 스펙과 가격, 국내가 글로벌보다 저렴한 이유를 정리했다."
  },
  {
    slug: "jeep-wrangler-laredo-2027",
    title: "지프 랭글러 라레도 부활 — 40년 만에 돌아온 탄색 소프트탑, 오프로드 스페셜 에디션 총정리",
    date: "2026-07-23",
    image: "jeep_wrangler_laredo_main.webp",
    categories: ["import"],
    tags: ["지프랭글러라레도", "오프로드SUV", "트웰브포트웰브", "지프윌리스", "스페셜에디션"],
    badge: "OFFROAD SPECIAL",
    badgeClass: "cat-sales",
    source: "Carscoops / TFLcar",
    desc: "지프가 매달 새 한정판을 선보이는 '트웰브 포 트웰브' 프로젝트 아홉 번째 주인공으로 1980년대의 아이콘 '랭글러 라레도'를 소환했다. 탄색 소프트탑과 버건디·골드 그래픽, Xtreme 35 오프로드 패키지까지 총정리했다."
  },
  {
    slug: "highway-toll-discount-multichild-disabled-2026",
    title: "다자녀·장애인·유공자 고속도로 통행료 할인 확대 — 대상·할인율·신청 방법",
    date: "2026-07-22",
    image: "seoul_tollgate_hipass.jpg",
    categories: ["news"],
    tags: ["고속도로통행료할인", "다자녀가구", "장애인통행료감면", "국가유공자", "하이패스"],
    badge: "POLICY UPDATE",
    badgeClass: "cat-sales",
    source: "농민신문",
    desc: "국토교통부가 유료도로법 시행령 개정안을 의결하며 다자녀가구와 장애인·국가유공자의 고속도로 통행료 감면을 확대했다. 할인율, 대상 차량 기준, 시행일, 신청 방법을 정리했다."
  },
  {
    slug: "car-subscription-long-term-rent-trend",
    title: "소유 대신 이용 — 차량 구독·장기렌트 서비스 확산의 이유",
    date: "2026-07-22",
    image: "kona_electric_charging.jpg",
    categories: ["news", "domestic"],
    tags: ["차량구독서비스", "장기렌트", "현대셀렉션", "기아플렉스", "카리스구독"],
    badge: "TREND INSIGHT",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "현대 셀렉션 360일 플랜, 기아 플렉스까지 완성차 업체들이 구독 서비스를 확대하고 있다. 장기렌트·리스와의 차이, 인기 차종과 요금을 정리했다."
  },
  {
    slug: "ev-conversion-subsidy-1million-won",
    title: "내연차 전환지원금 100만 원 신설 — 3년 이상 된 차 처분하고 전기차로 갈아타면",
    date: "2026-07-22",
    image: "kia_ev6_official.jpg",
    categories: ["news", "electric"],
    tags: ["전환지원금", "전기차보조금", "내연차전기차전환", "조기폐차", "기후에너지환경부"],
    badge: "EV POLICY",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "3년 이상 된 내연기관차를 폐차하거나 팔고 전기차를 사면 국고보조금에 최대 100만 원이 추가된다. 대상 조건과 실제 수령액을 정리했다."
  },
  {
    slug: "ev-subsidy-evaluation-system-july-2026",
    title: "7월 전기차 보조금 개편 — 제작·수입사 평가제 시행, 테슬라 통과·BYD 탈락",
    date: "2026-07-22",
    image: "tesla_model_y.jpg",
    categories: ["news", "electric"],
    tags: ["전기차보조금", "평가제", "테슬라", "BYD", "공급망기여도", "기후에너지환경부"],
    badge: "EV POLICY",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "기후에너지환경부가 전기차 보급사업 수행자 평가기준을 확정, 7월 1일부터 평가 통과 기업의 차량만 보조금 지원 대상이 됐다. 테슬라는 통과, BYD·지커는 탈락했다."
  },
  {
    slug: "kia-stonic-diesel-used-buy-guide",
    title: "신차에서 사라진 디젤, 중고 스토닉이 대안인 이유 — 연비·가격 총정리",
    date: "2026-07-21",
    image: "stonic_diesel_front.jpg",
    categories: ["news", "domestic"],
    tags: ["기아스토닉", "디젤SUV", "중고차추천", "연비", "스토닉디젤"],
    badge: "USED CAR PICK",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "카니발·투싼·스타리아까지 디젤이 속속 단종되는 지금, 기아 스토닉 디젤은 여전히 실속 있는 대안이다. 엔진 스펙, 연비, 신차 대비 중고 시세까지 총정리했다."
  },
  {
    slug: "driving-license-subsidy-2026-h2",
    title: "2026 하반기 운전면허 지원금 총정리 — 지역별 금액·대상·신청 방법",
    date: "2026-07-21",
    image: "driving_license_exam_office.jpg",
    categories: ["news"],
    tags: ["운전면허지원금", "청년지원금", "자립준비청년", "디딤돌운전면허지원센터", "운전상식"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "최소 5만 원부터 최대 70만 원까지, 지자체별로 제각각인 청년 운전면허 취득 지원금. 대상·신청 방법·필요 서류부터 자립준비청년·국가유공자 지원까지 총정리했다."
  },
  {
    slug: "kgm-project-s10-flagship-suv",
    title: "KGM '프로젝트 S10', 렉스턴 후속 플래그십 SUV — 팰리세이드에 던지는 승부수",
    date: "2026-07-21",
    image: "rexton_current_uk.jpg",
    categories: ["news", "domestic"],
    tags: ["KGM", "프로젝트S10", "SE10", "렉스턴", "아리랑", "팰리세이드", "REEV"],
    badge: "PROJECT S10",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "가격 경쟁력, 디젤을 배제한 파워트레인 전환, 렉스턴을 잇는 차세대 플래그십. KGM이 대형 SUV 시장에 던지는 세 가지 승부수를 정리했다."
  },
  {
    slug: "rainy-season-hydroplaning-tire-check",
    title: "장마철 빗길 안전운전 — 수막현상(하이드로플레이닝) 예방과 타이어 마모도 체크법",
    date: "2026-07-20",
    image: "rain_driving_pov.jpg",
    categories: ["news"],
    tags: ["수막현상", "하이드로플레이닝", "빗길운전", "타이어마모", "장마철", "운전상식"],
    badge: "DRIVING TIPS",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "장마철 빗길 사고의 주범, 수막현상(하이드로플레이닝)이 발생하는 원리와 예방법을 정리했다. 동전으로 확인하는 타이어 마모도 체크법부터 대처요령까지 총정리."
  },
  {
    slug: "cadillac-escalade-iq-review",
    title: "캐딜락 에스컬레이드 IQ·IQL — 750마력 710km 전동화 플래그십, 국내외 정보 총정리",
    date: "2026-07-20",
    image: "escalade_iq_front.jpg",
    categories: ["import", "electric"],
    tags: ["캐딜락", "에스컬레이드IQ", "에스컬레이드IQL", "전기차", "수입차", "슈퍼크루즈"],
    badge: "IMPORT EV",
    badgeClass: "cat-hyundai",
    source: "카프리즘 기획 기사",
    desc: "완전 전동화 플래그십 SUV 에스컬레이드 IQ에 롱바디 IQL이 합류했다. 750마력 듀얼모터, 710km 주행거리, 55인치 커브드 디스플레이까지 국내외 정보를 총정리."
  },
  {
    slug: "bentley-continental-gt-s-gtc-s-korea",
    title: "벤틀리 더 뉴 컨티넨탈 GT S·GTC S 국내 출시 — 680마력 하이브리드, 3억 6,850만 원부터",
    date: "2026-07-20",
    image: "bentley_gt_s_official.jpg",
    categories: ["import"],
    tags: ["벤틀리", "컨티넨탈GT", "컨티넨탈GTC", "수입차", "고성능", "하이브리드"],
    badge: "LUXURY IMPORT",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "벤틀리모터스코리아가 더 뉴 컨티넨탈 GT S와 GTC S를 국내 출시했다. 680마력 하이 퍼포먼스 하이브리드와 국내 가격까지 총정리했다."
  },
  {
    slug: "aston-martin-dreadnought-mw4",
    title: "전장을 달리는 슈퍼카 — 콜 오브 듀티 MW4의 애스턴마틴 드레드노트 완전 분석",
    date: "2026-07-19",
    image: "am_dreadnought_main.jpg",
    categories: ["import"],
    tags: ["애스턴마틴", "드레드노트", "COD", "MW4", "게임차량", "전술SUV"],
    badge: "GAME × AUTO",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "인피니티 워드와 애스턴마틴이 협업해 탄생시킨 게임 전용 전술 SUV '드레드노트'의 디자인, 퍼포먼스, 전술 장비 등 모든 스펙을 완전 해부합니다."
  },
  {
    slug: "genesis-gv60-gv70-electrified-2027",
    title: "제네시스 '2027 GV60'·'2027 GV70 전동화 모델' 판매 개시 — 가격은 동결, 사양은 강화",
    date: "2026-07-19",
    image: "genesis_gv60_2027_official.jpg",
    categories: ["domestic", "electric"],
    tags: ["제네시스", "GV60", "GV70", "전동화", "전기차", "연식변경"],
    badge: "GENESIS EV",
    badgeClass: "cat-genesis",
    source: "카프리즘 기획 기사",
    desc: "제네시스가 고객 편의 사양을 강화하고 선택권을 확대한 연식변경 모델 '2027 GV60'과 '2027 GV70 전동화 모델' 판매를 시작했다. 가격은 동결하고 사양은 강화했다."
  },
  {
    slug: "k5-2026-facelift-review",
    title: "기아 K5 상품성 강화 연식변경, 2,763만 원부터 — 국내외 리뷰 종합",
    date: "2026-07-18",
    image: "k5_side_exterior.jpg",
    categories: ["domestic", "reviews"],
    tags: ["기아", "K5", "연식변경", "상품성강화", "시승기", "리뷰"],
    badge: "FACELIFT REVIEW",
    badgeClass: "cat-hyundai",
    source: "카프리즘 기획 기사",
    desc: "기아가 상품성을 강화한 K5 연식변경 모델을 출시했다. 시작가 2,763만 원, 신설 '베스트 셀렉션' 트림, 강화된 편의·안전 사양까지 국내외 리뷰를 취합해 정리했다."
  },
  {
    slug: "seltos-hybrid-review-2026",
    title: "드디어 하이브리드 탑재! 3세대 '기아 셀토스 풀체인지' 시승기 및 가성비 추천 트림",
    date: "2026-07-17",
    image: "seltos_official.png",
    categories: ["domestic", "reviews"],
    tags: ["기아", "셀토스", "하이브리드", "풀체인지", "시승기", "트림추천"],
    badge: "TEST DRIVE",
    badgeClass: "cat-hyundai",
    source: "카프리즘 기획 기사",
    desc: "가솔린 위주였던 셀토스가 하이브리드 파워트레인을 얹고 3세대로 완전히 탈바꿈했다. 실주행 연비와 정숙성, 커진 체격, 가성비 트림 가이드까지 총정리했다."
  },
  {
    slug: "july-promotions-2026",
    title: "7월 여름 한정 최대 400만 원 할인! 지금 당장 계약해야 이득인 가성비 국산·수입 세단",
    date: "2026-07-17",
    image: "sonata_official.png",
    categories: ["news", "domestic"],
    tags: ["할인", "프로모션", "쏘나타", "수입차", "BMW", "아우디", "대기기간"],
    badge: "FINANCE INSIGHT",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "7월 자동차 제조사들의 여름 한정 파격 할인 혜택 정리! 쏘나타 디 엣지부터 BMW 5시리즈, 아우디 A8 등 수입 세단 할인율과 신차 대기 기간 가이드를 드립니다."
  },
  {
    slug: "tesla-vs-byd-2026",
    title: "테슬라 모델 Y 독주에 브레이크? 가성비 끝판왕 'BYD 돌핀' 한국 상륙 분석",
    date: "2026-07-17",
    image: "byd_dolphin.jpg",
    categories: ["news", "import", "electric"],
    tags: ["전기차", "테슬라", "BYD", "모델Y", "돌핀", "보조금"],
    badge: "IMPORT EV",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "국내 수입 전기차 1위 테슬라 모델 Y에 맞서 초가성비로 무장한 BYD 돌핀과 씨라이언 7의 국내 상륙을 분석했다. 7월 보조금 개정 탈락 소식까지 총정리했습니다."
  },
  {
    slug: "hybrids-and-suvs-2026",
    title: "지금 사면 후회할까? 2026 하반기 출시 예정 하이브리드 & SUV 주목 신차 5종",
    date: "2026-07-17",
    image: "gv80_hybrid.png",
    categories: ["news", "domestic"],
    tags: ["하이브리드", "SUV", "신차", "기아", "현대차", "제네시스"],
    badge: "TREND INSIGHT",
    badgeClass: "cat-sales",
    source: "카프리즘 기획 기사",
    desc: "2026년 하반기 시장을 뒤흔들 하이브리드 및 SUV 신차 5종 분석. 셀토스 하이브리드, GV80 하이브리드, 그랜저 페이스리프트 등 구매 타이밍 가이드를 드립니다."
  },
  {
    slug: "sales-ranking-2026-06",
    title: "2026년 6월 국산차 판매량 TOP 10, 그랜저가 정상 탈환",
    date: "2026-07-14",
    image: "grandeur_official.png",
    categories: ["news", "domestic"],
    tags: ["그랜저", "셀토스", "쏘렌토", "카니발", "스포티지", "판매량"],
    badge: "SALES RANKING",
    badgeClass: "cat-sales",
    source: "카이즈유 / 한국자동차연구원 외",
    desc: "2026년 6월 국산차 내수 판매 12만 826대, 전월 대비 25.5% 반등. 그랜저 1위 복귀, 셀토스 최대 상승폭까지 TOP 10 판매 순위를 정리했다."
  },
  {
    slug: "avante-vs-byd-busan-2026",
    title: "아반떼 vs BYD, 부산모빌리티쇼가 보여준 하이브리드 전쟁",
    date: "2026-07-12",
    image: "avante.png",
    categories: ["news", "domestic", "import"],
    tags: ["아반떼", "BYD", "제네시스", "하이브리드", "전기차"],
    badge: "HYUNDAI · BYD",
    badgeClass: "cat-hyundai",
    source: "오토트리뷴 / 매일경제",
    desc: "2026 부산모빌리티쇼 결산. 현대차 신형 아반떼와 BYD 씨라이언6 DM-i가 맞붙은 하이브리드 격전, 제네시스 GMR-001 하이퍼카까지 한눈에 정리했다."
  }
];
